### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by ghost** [maoberlehner/node-sass-glob-importer#9]
While using `node-sass-glob-importer` to handle glob patterns in a `@import` statement, I encountered an issue on Windows (though not on Linux).

Specifically the following error is thrown by `node-sass` or `libsass`:

``` json
{
  "status": 1,
  "file": "./components/*.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: C:UsershbettsWorkspacenode-sass-windows\npp\fomponents\fomponents.scss\nParent style sheet: ./components/*.scss",
  "formatted": "Error: File to import not found or unreadable: C:UsershbettsWorkspacenode-sass-windows\n       pp\fomponents\fomponents.scss\n       Parent style sheet: ./components/*.scss\n        on line 1 of components/*.scss\n>> @import 'C:\\Users\\hbetts\\Workspace\\node-sass-windows\\app\\components\\components\n   ^\n"
}
```

I am using the following project to demonstrate the issue: https://gitlab.com/hutson/node-sass-windows

You may clone the project, run `npm install` to get all the build dependencies, and then run `npm run sass` to invoke `node-sass` with this importer.

The demonstration project has a file named `app.scss` under the `app/` directory that contains a single import glob statement:

``` sass
@import './components/*.scss';
```

That import statement leads this glob importer to find the `app/components/components.scss` file, and generate the following content:

``` sass
@import 'C:\Users\hbetts\Workspace\node-sass-windows\app\components\components.scss';
```

First, I take that content and place it in a new file called `app/example.scss`.

I then change the contents of `app/components/components.scss` to remove the import glob statement.

Lastly I run the following command over the project:

``` bash
./node_modules/.bin/node-sass app/example.scss -o dist
```

I end up with a very similar error:

``` json
{
  "status": 1,
  "file": "C:/Users/hbetts/Workspace/node-sass-windows/app/example.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: C:UsershbettsWorkspacenode-sass-windows\npp\fomponents\fomponents.scss\nParent style sheet: C:/Users/hbetts/Workspace/node-sass-windows/app/example.scss",
  "formatted": "Error: File to import not found or unreadable: C:UsershbettsWorkspacenode-sass-windows\n       pp\fomponents\fomponents.scss\n       Parent style sheet: C:/Users/hbetts/Workspace/node-sass-windows/app/example.scss\n        on line 1 of app/example.scss\n>> @import 'C:\\Users\\hbetts\\Workspace\\node-sass-windows\\app\\components\\components\n   ^\n"
}
```

Next I change the contents of `app/example.scss` from:

``` sass
@import 'C:\Users\hbetts\Workspace\node-sass-windows\app\components\components.scss';
```

To:

``` sass
@import 'C:/Users/hbetts/Workspace/node-sass-windows/app/components/components.scss';
```

Notice how I switch `\` to `/`.

I run the above command again and it succeeds:

``` bash
./node_modules/.bin/node-sass app/example.scss -o dist
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\hbetts\Workspace\node-sass-windows\dist\example.css
```

I end up with the desired content:

``` css
#red {
  background: red; }
```

It seems `node-sass` can't handle backslashes in Windows file paths.

Therefore does it make sense to process the absolute file path, converting backslashes to forward slashes, prior to generating the file content to pass to `node-sass`?

**Comment by maoberlehner** [comment]
Thank you for your detailed explanation of the problem.

I'll boot up my windows machine and look into this ;)

**Comment by maoberlehner** [comment]
Ok, i "fixed" this with version 2.0.3 - although I think this should be fixed in node-sass or libsass directly. It would be really cool if you could investigate further and create an issue for the node-sass or libsass project(s).

I do not close this issue as a reminder that I should remove the hack from the module if this gets fixed.

**Comment by ghost** [comment]
@maoberlehner I suspect it's probably related to how CSS handles [escape sequences](http://reference.sitepoint.com/css/cssescapenotation). The backslash triggering that behavior, 

However, I've gone ahead and filed an issue with `libsass`: sass/libsass/issues/2181

**Comment by maoberlehner** [comment]
This is now obsolete because of https://github.com/maoberlehner/node-sass-glob-importer/commit/bdc11ed1c630177a5d0178dc27a180fa62fbbf9e
